Controllers/FolderController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static NuGet.Packaging.PackagingConstants;

namespace DriveUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FolderController : Controller
    {
        FolderManager folderManager = new FolderManager(new EFFolderDal());

        Context context = new Context();

        public IActionResult GetFolders()
        {
            var folders = folderManager.GetFolders();
            return View(folders);
        }

        public IActionResult FolderDetails(int id)
        {
            var folderValues = folderManager.GetByID(id);
            var parentFolder = context.Folders.FirstOrDefault(x => x.FolderID == folderValues.RootFolderID);
            if (parentFolder != null)
            {
                ViewBag.ParentFolderName = parentFolder.FolderName;
            }
            else
            {
                ViewBag.ParentFolderName = "This folder has not a parent folder.";
            }

            return View(folderValues);
        }

        [HttpGet]
        public IActionResult AddFolder()
        {
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;
            return View();
        }

        [HttpPost]
        public IActionResult AddFolder(Folder folder)
        {
            FolderValidator validator = new FolderValidator();
            ValidationResult results = validator.Validate(folder);

            if (results.IsValid)
            {
                folderManager.FolderAdd(folder);
                return RedirectToAction("GetFolders");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public IActionResult FolderDelete(int id)
        {
            var folderValue = folderManager.GetByID(id);
            folderManager.FolderRemove(folderValue);
            return RedirectToAction("GetFolders");
        }

        [HttpGet]
        public IActionResult FolderUpdate(int id)
        {
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;
            var folderValuesforView = folderManager.GetByID(id);
            return View(folderValuesforView);
        }
        [HttpPost]
        public IActionResult FolderUpdate(Folder folder)
        {
            FolderValidator validator = new FolderValidator();
            ValidationResult results = validator.Validate(folder);
            if (results.IsValid)
            {
                folderManager.FolderUpdate(folder);
                return RedirectToAction("GetFolders");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

    }
}

Controllers/RoleAuthorityController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DriveUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAuthorityController : Controller
    {
        RoleAuthorityManager roleAuthorityManager = new RoleAuthorityManager(new EFRoleAuthorityDal());
        RoleManager roleManager = new RoleManager(new EFRoleDal());
        FolderManager folderManager = new FolderManager(new EFFolderDal());
        
        public IActionResult GetRoleAuthorities()
        {
            var roleAuthorities = roleAuthorityManager.GetRoleAuthorities();
            return View(roleAuthorities);
        }

        public IActionResult RoleAuthorityDetails(int id)
        {
            var roleAuthorityValues = roleAuthorityManager.GetByID(id);
            return View(roleAuthorityValues);
        }

        [HttpGet]
        public IActionResult AddRoleAuthorities()
        {
            List<SelectListItem> roleValues = (from x in roleManager.GetRoles()
                                               select new SelectListItem
                                               {
                                                   Text = x.RoleName,
                                                   Value = x.RoleID.ToString()
                                               }).ToList();
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                               select new SelectListItem
                                               {
                                                   Text = x.FolderName,
                                                   Value = x.FolderID.ToString()
                                               }).ToList();
            ViewBag.Roles = roleValues;
            ViewBag.Folders = folderValues;

            return View();
        }

        [HttpPost]
        public IActionResult AddRoleAuthorities(RoleAuthority roleAuthority)
        {
            RoleAuthorityValidator validator = new RoleAuthorityValidator();
            ValidationResult results = validator.Validate(roleAuthority);
            if(results.IsValid)
            {
            roleAuthorityManager.AddRoleAuthortiy(roleAuthority);
            return RedirectToAction("GetRoleAuthorities");
            } else
            {
                foreach(var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult RemoveRoleAuthority(int id)
        {
            var roleAuthorityValues = roleAuthorityManager.GetByID(id);
            roleAuthorityManager.RoleAuthorityRemove(roleAuthorityValues);
            return RedirectToAction("GetRoleAuthorities");
        }

        [HttpGet]
        public IActionResult RoleAuthorityUpdate(int id)
        {
            List<SelectListItem> roleValues = (from x in roleManager.GetRoles()
                                               select new SelectListItem
                                               {
                                                   Text = x.RoleName,
                                                   Value = x.RoleID.ToString()
                                               }).ToList();
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Roles = roleValues;
            ViewBag.Folders = folderValues;
            var roleAuthorityValues = roleAuthorityManager.GetByID(id);
            return View(roleAuthorityValues);
        }

        [HttpPost]
        public IActionResult RoleAuthorityUpdate(RoleAuthority roleAuthority)
        {
            RoleAuthorityValidator validator = new RoleAuthorityValidator();
            ValidationResult results = validator.Validate(roleAuthority);
            if (results.IsValid)
            {
                roleAuthorityManager.RoleAuthorityUpdate(roleAuthority);
                return RedirectToAction("GetRoleAuthorities");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

Controllers/RoleController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DriveUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager roleManager = new RoleManager(new EFRoleDal());
        FolderManager folderManager = new FolderManager(new EFFolderDal());

        Context context = new Context();

        public IActionResult GetRoles()
        {
            var roles = roleManager.GetRoles();
            return View(roles);
        }

        public IActionResult RoleDetails(int id)
        {
            var roleValues = roleManager.GetByID(id);
            var roleAuthoritiesValues = context.RoleAuthorities.FirstOrDefault(x => x.RoleID ==  roleValues.RoleID);
            if(roleAuthoritiesValues != null)
            {
                ViewBag.RoleFolder = roleAuthoritiesValues.Folder.FolderName;
            } else
            {
                ViewBag.RoleFolder = "This role has not folder.";
            }
            return View(roleValues);
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddRole(Role role)
        {
            RoleValidator validator = new RoleValidator();
            ValidationResult results = validator.Validate(role);

            if (results.IsValid)
            {
                roleManager.AddRole(role);
                return RedirectToAction("GetRoles");
            } else
            {
                foreach(var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult RemoveRole(int id) 
        {
            var roleValues = roleManager.GetByID(id);
            roleManager.RoleRemove(roleValues);
            return RedirectToAction("GetRoles");
        }
        [HttpGet]
        public IActionResult RoleUpdate(int id)
        {
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;
            var roleValues = roleManager.GetByID(id);
            return View(roleValues);
        }

        [HttpPost]
        public IActionResult RoleUpdate(Role role)
        {
            RoleValidator validator = new RoleValidator();
            ValidationResult results = validator.Validate(role);

            if (results.IsValid)
            {
                roleManager.RoleUpdate(role);
                return RedirectToAction("GetRoles");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

Controllers/UserController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DriveUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        UserManager userManager = new UserManager(new EFUserDal());
        RoleManager roleManager = new RoleManager(new EFRoleDal());

        Context context = new Context();


        public IActionResult GetUsers()
        {
            var users = userManager.GetUsers();
            return View(users);
        }


        public IActionResult UserDetails(int id)
        {
            var userValues = userManager.GetByID(id);
            var userAuthorityValues = context.UserAuthorities.FirstOrDefault(x => x.UserID == userValues.UserID);
            ViewBag.UserAuthorityValues = userAuthorityValues;
            return View(userValues);
        }


        [HttpGet]
        public IActionResult AddUser()
        {
            List<SelectListItem> roleValues = (from x in roleManager.GetRoles()
                                               select new SelectListItem
                                               {
                                                   Text = x.RoleName,
                                                   Value = x.RoleID.ToString()
                                               }).ToList();
            ViewBag.Roles = roleValues;
            return View();
        }

        [HttpPost]
        public IActionResult AddUser(User user)
        {
            UserValidator validator = new UserValidator();
            ValidationResult results = validator.Validate(user);

            if (results.IsValid)
            {
                userManager.AddUser(user);
                return RedirectToAction("GetUsers");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public IActionResult RemoveUser(int id)
        {
            var userValues = userManager.GetByID(id);
            userManager.DeleteUser(userValues);
            return RedirectToAction("GetUsers");
        }

        [HttpGet]
        public IActionResult UserUpdate(int id)
        {
            List<SelectListItem> roleValues = (from x in roleManager.GetRoles()
                                               select new SelectListItem
                                               {
                                                   Text = x.RoleName,
                                                   Value = x.RoleID.ToString()
                                               }).ToList();
            ViewBag.Roles = roleValues;
            var userValues = userManager.GetByID(id);
            return View(userValues);
        }
        [HttpPost]
        public IActionResult UserUpdate(User user)
        {
            UserValidator validator = new UserValidator();
            ValidationResult results = validator.Validate(user);

            if (results.IsValid)
            {
                userManager.UserUpdate(user);
                return RedirectToAction("GetUsers");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DriveUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DriveUI.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <p class="navbar-brand" style="margin-top:1%;">MYDrive</p>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between">
                    @if (accessor.HttpContext.Session.GetString("UserRole") != null && accessor.HttpContext.Session.GetString("UserRole") == "Admin")
                    {

                        <ul class="navbar-nav flex-grow-0">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetUsers">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Folder" asp-action="GetFolders">Folders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Document" asp-action="GetDocumentList">Documents</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="GetRoles">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RoleAuthority" asp-action="GetRoleAuthorities">Role Authority</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAuthority" asp-action="GetUserAuthorities">User Authority</a>
                            </li>
                        </ul>
                    }
                    @if (accessor.HttpContext.Session.GetString("UserRole") != null && (accessor.HttpContext.Session.GetString("UserRole") != "Admin" && accessor.HttpContext.Session.GetString("UserRole") != "No Role"))
                    {
                        <ul class="navbar-nav flex-grow-0">
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/Document/GetDocumentListByRole/@accessor.HttpContext.Session.GetInt32("UserID")">Documents</a>
                            </li>
                        </ul>
                    }
                    @if (accessor.HttpContext.Session.GetString("UserName") != null)
                    {
                        <div class="nav-item text-dark" style="display:flex; align-items:center;">
                            @if (accessor.HttpContext.Session.GetString("UserRole") != "Admin")
                            {
                                <form method="post" asp-action="GetDocumentListByRole" asp-controller="Document" style="display:flex; align-items:center; margin-right:15px;">
                                    <span class="material-symbols-outlined" style="margin-right:15px;">
                                        search
                                    </span>
                                    <input type="text" name="searchTerm" placeholder="Search Document..." class="form-control" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-action="GetDocumentList" asp-controller="Document" style="display:flex; align-items:center; margin-right:15px;">
                                    <span class="material-symbols-outlined" style="margin-right:15px;">
                                        search
                                    </span>
                                    <input type="text" name="searchTerm" placeholder="Search Document..." class="form-control" />
                                </form>
                            }

                            <a style="margin-right:15px;" class="btn btn-outline-success text-success" href="/Login/MyProfile/@accessor.HttpContext.Session.GetInt32("UserID")">
                                @accessor.HttpContext.Session.GetString("UserName")'s Profile
                            </a>

                            <a class="btn btn-outline-danger" asp-area="" asp-controller="Login" asp-action="Logout">
                                @accessor.HttpContext.Session.GetString("UserName") Log Out!
                            </a>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid" style="display:flex; align-items:center;">
            Developed by <a class="nav-link text-dark" href="https://www.linkedin.com/in/orhangazibarak/">
                Orhan Gazi Barak
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>