Controllers/DocumentController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.Entity;

namespace DriveUI.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        DocumentManager documentManager = new DocumentManager(new EFDocumentDal());
        FolderManager folderManager = new FolderManager(new EFFolderDal());
        private readonly IWebHostEnvironment? webHostEnvironment;
        public readonly IHttpContextAccessor? accessor;

        Context context = new Context();

        public DocumentController(IWebHostEnvironment webHostEnvironment, IHttpContextAccessor accessor)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.accessor = accessor;
        }

        public async Task<IActionResult> GetDocumentList(string searchTerm)
        {
            var documents = from doc in context.Documents select doc;

            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            if (!string.IsNullOrEmpty(searchTerm))
            {
                documents = documents.Where(s => s.DocumentName.Contains(searchTerm));
            }
            ViewBag.Folders = folderValues;
            return View(await documents.ToListAsync());
        }

        public async Task<IActionResult> GetDocumentListByRole(int id, string searchTerm)
        {
            var user = context.Users.FirstOrDefault(x => x.UserID == id);
            string userRole = "";
            if (user != null)
                userRole += user.Role.RoleName;
            var documentsByRole = context.Documents.Where(x => x.Role.RoleName == userRole);

            if (!string.IsNullOrEmpty(searchTerm))
            {
                documentsByRole = documentsByRole.Where(s => s.DocumentName.Contains(searchTerm));
            }
            return View(await documentsByRole.ToListAsync());
        }

        [HttpGet]
        public IActionResult Upload()
        {
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 where x.FolderName != "root"
                                                 select new SelectListItem
                                                 {
                                                     Text = getFoldersPath(x),
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file, Document document)
        {
            string absolutePath;
            string[] splitedAbsolutePath;
            string folderPath = "";
            string oldFileName = file.FileName;
            string fileType = file.ContentType;
            string newFileName = Guid.NewGuid().ToString();
            string folderRole;

            document.DocumentName = oldFileName;
            document.Guid = newFileName;
            document.DocumentType = fileType;

            int folderID = document.FolderID;

            var folderValues = context.Folders.FirstOrDefault(x => x.FolderID == folderID);

            if (folderValues != null)
                folderPath = getFoldersPath(folderValues);

            absolutePath = Path.Combine("wwwroot\\Upload\\", folderPath);

            if (!Directory.Exists(absolutePath))
            {
                Directory.CreateDirectory(absolutePath);
            }

            using (var fileStream = new FileStream(Path.Combine(absolutePath, newFileName), FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
                TempData["FileUploadSuccess"] = "File upload success.";
            }

            splitedAbsolutePath = absolutePath.Split("\\");

            folderRole = splitedAbsolutePath[3];

            var role = context.Roles.FirstOrDefault(x => x.RoleName == folderRole);
            if (role != null)
                document.RoleID = role.RoleID;

            documentManager.DocumentAdd(document);

            if (accessor.HttpContext.Session.GetString("UserRole") != null && accessor.HttpContext.Session.GetString("UserRole") == "Admin")
            {
                return RedirectToAction("GetDocumentList");
            }
            else
            {
                return RedirectToAction("GetDocumentListByRole/" + accessor.HttpContext.Session.GetInt32("UserID"));
            }

        }

        public IActionResult DocumentDetailsView(int id)
        {
            var documentValues = documentManager.GetByID(id);

            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = getFoldersPath(x),
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;

            return View(documentValues);
        }
        [HttpGet]

        public IActionResult AddDocument()
        {
            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.FolderName,
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;
            return View();
        }


        [HttpPost]

        public IActionResult AddDocument(Document document)
        {
            DocumentValidator validator = new DocumentValidator();
            ValidationResult results = validator.Validate(document);
            if (results.IsValid)
            {
                documentManager.DocumentAdd(document);
                return RedirectToAction("GetDocumentList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public IActionResult DeleteDocument(int id)
        {
            string folderPath = "";
            string filePath = "";

            var documentValue = documentManager.GetByID(id);

            int folderID = documentValue.FolderID;

            var folderValues = context.Folders.FirstOrDefault(x => x.FolderID == folderID);

            if (folderValues != null)
                folderPath = getFoldersPath(folderValues);

            filePath += Path.Combine(folderPath, documentValue.Guid);

            if (System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);

            documentManager.DocumentRemove(documentValue);
            return RedirectToAction("GetDocumentList");
        }
        [HttpGet]
        public IActionResult DocumentUpdate(int id)
        {
            var documentValues = documentManager.GetByID(id);

            List<SelectListItem> folderValues = (from x in folderManager.GetFolders()
                                                 where x.FolderName != "root"
                                                 select new SelectListItem
                                                 {
                                                     Text = getFoldersPath(x),
                                                     Value = x.FolderID.ToString()
                                                 }).ToList();
            ViewBag.Folders = folderValues;

            return View(documentValues);
        }

        [HttpPost]
        public IActionResult DocumentUpdate(Document document)
        {
            string sourceFolderPath = "wwwroot\\Upload\\";
            string sourceAbsolutePath = "";

            string destinationFolderPath = "wwwroot\\Upload\\";
            string destinationAbsolutePath = "";
            string[] splitedDestinationAbsolutePath;
            string newDocumentRole;

            var documentNowValues = context.Documents.FirstOrDefault(x => x.DocumentID == document.DocumentID);
            var nowFolder = context.Folders.FirstOrDefault(x => x.FolderID == documentNowValues.FolderID);

            if (documentNowValues != null)
            {
                if (nowFolder != null)
                    sourceFolderPath += getFoldersPath(nowFolder);

                sourceAbsolutePath = Path.Combine(sourceFolderPath, documentNowValues.Guid);
            }

            var destinationFolder = context.Folders.FirstOrDefault(x => x.FolderID == document.FolderID);

            if (destinationFolder != null)
                destinationFolderPath += getFoldersPath(destinationFolder);

            if (!Directory.Exists(destinationFolderPath))
            {
                Directory.CreateDirectory(destinationFolderPath);

            }

            destinationAbsolutePath = Path.Combine(destinationFolderPath, document.Guid);

            splitedDestinationAbsolutePath = destinationAbsolutePath.Split("\\");

Views/Document/AddDocument.cshtml
@model EntityLayer.Concrete.Document

<form class="form-group" method="post">
    <div style="width:500px; height:auto;">
        <input type="text" placeholder="Document Name" name="DocumentName" class="form-control" />
        <p class="text-danger text-center">@Html.ValidationMessageFor(x => x.DocumentName)</p>
    </div>

@*    <div style="width:500px; height:auto;">
        @Html.DropDownListFor(x => x.DocumentTypeID, (List<SelectListItem>)ViewBag.DocumentTypes, new {@class = "form-control"})
        <p class="text-danger text-center">@Html.ValidationMessageFor(x => x.DocumentTypeID)</p>
    </div>*@

    <div style="width:500px; height:auto;">
        @Html.DropDownListFor(x => x.FolderID, (List<SelectListItem>)ViewBag.Folders, new {@class = "form-control"})
        <p class="text-danger text-center">@Html.ValidationMessageFor(x => x.FolderID)</p>
    </div>
    <div style="display:flex; justify-content:space-between;">
        <button class="btn btn-primary">Add</button>
        <a class="btn btn-light" asp-action="Upload">Upload</a>
    </div>
</form>

Views/Document/DocumentDetailsView.cshtml
@model EntityLayer.Concrete.Document

@{
    ViewData["Title"] = "Document Deatils View";
}

<h1>@Model.DocumentName's Deatils</h1>
<hr />

<div>

    <dl class="row">
        <dt class="col-sm-2">
            Document ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DocumentID)
        </dd>
        <dt class="col-sm-2">
            Document Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DocumentName)
        </dd>
        <dt class="col-sm-2">
            Folder Name
        </dt>
        <dd class="col-sm-10">
            @Html.DropDownListFor(model => model.FolderID, (List<SelectListItem>)ViewBag.Folders,new {@class = "form-control", disabled = "true"})
        </dd>
        <dt class="col-sm-2">
            Document Type Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DocumentType)
        </dd>
        <dt class="col-sm-2">
            Document Role
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role.RoleName)
        </dd>
    </dl>
    <div style="display:flex; justify-content:space-between; margin-top:15px;">
        <a href="/Document/DocumentUpdate/@Model.DocumentID" class="btn btn-primary">Update</a>
    </div>
</div>

Views/Document/DocumentUpdate.cshtml
@model EntityLayer.Concrete.Document

@{
    ViewData["Title"] = "Document Update";
}

<h1>Document Update</h1>
<hr />
<h2>@Html.DisplayFor(x => x.DocumentName)</h2>
<div class="row">
    <div class="col-md-4" style="margin:auto">
        <form asp-action="DocumentUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-bottom:15px;">
                <label asp-for="DocumentID" class="control-label" hidden>ID</label>
                <input asp-for="DocumentID" class="form-control" hidden />
                <span asp-validation-for="DocumentID" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <label asp-for="Guid" class="control-label" hidden>Guid</label>
                <input asp-for="Guid" class="form-control" hidden/>
                <span asp-validation-for="Guid" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <label asp-for="DocumentName" class="control-label">Name</label>
                <input asp-for="DocumentName" class="form-control" />
                <span asp-validation-for="DocumentName" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <label asp-for="FolderID" class="control-label">Folder Name</label>
                @Html.DropDownListFor(x => x.FolderID, (List<SelectListItem>)ViewBag.Folders, new {@class = "form-control"})
                <span asp-validation-for="FolderID" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:flex; justify-content:space-between">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Document/GetDocumentList.cshtml
@model IEnumerable<EntityLayer.Concrete.Document>

@{
    ViewData["Title"] = "Get Document List";
}

<div style="display:flex; justify-content:center;">
    <a href="/Document/Upload" class="btn btn-outline-secondary" style="display:flex; align-items:center;">
        <span class="material-symbols-outlined">
            add_circle
        </span>
        New Document
    </a>
</div>

<br />

<table class="table table-hover table-striped text-center">
    <thead>
        <tr>
            <th>
                Document Name
            </th>
            <th>
                Folder Name
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DocumentName)
                </td>
                <td>
                    @Html.DropDownListFor(modelItem => item.FolderID, (List<SelectListItem>)ViewBag.Folders,new {@class = "form-control", disabled = "true"})
                </td>
                <td>
                    <div style="display:flex; justify-content:space-evenly;">
                        <a href="/Document/DownloadFile/@item.DocumentID" class="btn btn-outline-success" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                download
                            </span>
                            Download
                        </a>
                        <a href="/Document/DocumentUpdate/@item.DocumentID" class="btn btn-outline-primary" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                            Edit
                        </a>
                        <a href="/Document/DocumentDetailsView/@item.DocumentID" class="btn btn-outline-info" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                info_i
                            </span>
                            Details
                        </a>
                        <a href="/Document/DeleteDocument/@item.DocumentID" class="btn btn-outline-danger" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                            Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Document/GetDocumentListByRole.cshtml
@model IEnumerable<EntityLayer.Concrete.Document>

@{
    ViewData["Title"] = "Get Document List";
}

<div style="display:flex; justify-content:center; margin-bottom:15px;">
    <a href="/Document/Upload" class="btn btn-outline-secondary" style="display:flex; align-items:center;">
        <span class="material-symbols-outlined">
            add_circle
        </span>
        New Document
    </a>
</div>

<br />

<table class="table table-hover table-striped text-center">
    <thead>
        <tr>
            <th>
                Document Name
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DocumentName)
                </td>
                <td>
                    <div style="display:flex; justify-content:space-evenly;">
                        <a href="/Document/DownloadFile/@item.DocumentID" class="btn btn-outline-success" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                download
                            </span>
                            Download
                        </a>
                        <a href="/Document/DocumentUpdate/@item.DocumentID" class="btn btn-outline-primary" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                            Edit
                        </a>
                        <a href="/Document/DocumentDetailsView/@item.DocumentID" class="btn btn-outline-info" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                info_i
                            </span>
                            Details
                        </a>
                        <a href="/Document/DeleteDocument/@item.DocumentID" class="btn btn-outline-danger" style="display:flex; align-items:center;">
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                            Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Document/Upload.cshtml
@model EntityLayer.Concrete.Document

<div style="display:flex; align-items:center; justify-content:center">
    <form class="form-group align-items-center" enctype="multipart/form-data" method="post" asp-controller="Document" asp-action="Upload">
        <input type="file" name="file" class="form-control" style="width:500px; margin-bottom:15px;" multiple />

        <div class="form-group" style="margin-bottom:15px;">
            <label asp-for="FolderID" class="control-label">Folder Name</label>
            @Html.DropDownListFor(x => x.FolderID, (List<SelectListItem>)ViewBag.Folders, new {@class = "form-control"})
            <span asp-validation-for="FolderID" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="margin-bottom:15px;">Upload File</button>

        @if (TempData["FileUploadSuccess"] != null)
        {
            <h1 class="text-success">@TempData["FileUploadSuccess"]</h1>
        }
    </form>
</div>